### ISSUE TITLE
mdns example panics on Windows in release mode, but not in debug mode

### ISSUE THREAD

**Issue by Dudemanjude** [bltavares/multicast-socket#14]
First of all, thanks for making such a nice crate. After looking at the source code, I realize what I would be getting into had I needed to implement multicast on all interfaces myself for both Windows and Linux. 😄 

But I am having a bit of a problem. Just like the title says, I can run the mdns example in debug mode, and it works perfectly fine, but it panics in release mode with this error:
```
thread 'main' panicked at 'could not broadcast message to ips being listened: Os { code: 10022, kind
: InvalidInput, message: "An invalid argument was supplied." }', examples\mdns.rs:25:10
```

I'm also running into this issue in my own project using this crate. It can send out a multicast (checked with Wireshark) in debug mode, but in release, it panics with the same error.

I have multiple different network adapters, WSL's vEthernet, VirtualBox's Host-Only Network, my WiFi adapter, Ethernet (that I'm not using), and ZeroTier One. I ended up on your crate due to my multicasts ending up on WSL's interface, rather than my WiFi adapter's.

If I can provide any more system information, or do some more testing, I'd be happy to help.

**Comment by bltavares** [comment]
Hello there. This is an interesting issue. I also have the same setup on my
development machine, including the ZeroTier One adapter and WSL vEthernet.

Indeed, running on release mode panics the sample example. I'm curious if
this is an issue on the sample or an optimization triggering a bug in the
library.

I currently don't have much time on my hands to troubleshoot this, but I
can test any patches on my dev environment to validate changes.
Sorry for not having time to help at this moment.

Kind regards,

Em qui., 5 de mai. de 2022 às 20:07, Dudemanjude ***@***.***>
escreveu:

**Comment by mon** [comment]
Out of curiosity, and since `windows-rs` is the new hotness, I rewrote the lib to use it. It changed absolutely nothing and produced the same error 😅 One red herring down!
