### ISSUE TITLE
What does Ipv4PacketInfo do?

### ISSUE THREAD

**Issue by eskimor** [bltavares/multicast-socket#6]
Hi!

First of all, thanks a lot for this library!

I would love to have some comment on [line](https://github.com/bltavares/multicast-socket/blob/master/src/unix.rs#L22) explaining what it does, as I don't find anything useful when googling. Thanks a lot!

**Comment by bltavares** [comment]
That sets the `IP_PKTINFO` [socket option](https://man7.org/linux/man-pages/man7/ip.7.html). That is needed to know which of the interfaces received the multicast packet.

As we are joining multiple interfaces, `recv` does not inform the appropriate interface received, only the bound address. We need to enable this option to get the original interface information using `recvmsg` and other OS-level methods.

There are more [references](https://github.com/bltavares/multicast-socket#references) to understand it better.

**Comment by eskimor** [comment]
Wow! Thanks a lot for the man page pointer. I studied the socket manpage, the sendmsg man page, the setsockopt man page, but I did not know about the ip man page, which finally documents stuff. Awesome! :-)
